language: node_js
node_js:
  - "0.12"

env:
  - SELENIUM_BROWSER=chrome VELOCITY_CI=1 CUCUMBER_TAIL=1 STRIPE_PK=pk_test_W7Cx4LDFStOIaJ2g5DufAIaE STRIPE_SK=sk_test_CEgjj8xNKSrQMUrqC4puiHxA

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - "npm install -g eslint"
  - "cd tests/cucumber && npm install"

script: "eslint . && meteor --test"
