quotations = [
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out. - John Wooden",
  "Innovation distinguishes between a leader and a follower. - Steve Jobs",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "To live a creative life, we must lose our fear of being wrong.",
  "If you are not willing to risk the usual you will have to settle for the ordinary. - Jim Rohn",
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. - Swami Vivekananda",
  "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
  "Good things come to people who wait, but better things come to those who go out and get them.",
  "If you do what you always did, you will get what you always got.",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly. - Proverb",
  "Successful entrepreneurs are givers and not takers of positive energy.",
  "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. - Vaibhav Shah",
  "Opportunities don't happen, you create them. - Chris Grosser",
  "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
  "If you don't value your time, neither will others. Stop giving away your time and talents- start charging for it. - Kim Garst",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
  "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
  "If you're going through hell keep going. - Winston Churchill",
  "The ones who are crazy enough to think they can change the world, are the ones that do.",
  "Don't raise your voice, improve your argument.",
  "What seems to us as bitter trials are often blessings in disguise.-  Oscar Wilde",
  "The meaning of life is to find your gift. The purpose of life is to give it away.",
  "The distance between insanity and genius is measured only by success. - Bruce Feirstein",
  "When you stop chasing the wrong things you give the right things a chance to catch you. - Lolly Daskal",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "No masterpiece was ever created by a lazy artist.",
  "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. - Nathaniel Hawthorne",
  "If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
  "Blessed are those who can give without remembering and take without forgetting.",
  "Do one thing every day that scares you.",
  "What's the point of being alive if you don't at least try to do something remarkable.",
  "Life is not about finding yourself. Life is about creating yourself. - Lolly Daskal",
  "Nothing in the world is more common than unsuccessful people with talent.",
  "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.",
  "Your problem isn't the problem. Your reaction is the problem.",
  "You can do anything, but not everything.",
  "Innovation distinguishes between a leader and a follower. - Steve Jobs",
  "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. - Ray Goforth",
  "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life. - Dr. APJ Kalam",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "The starting point of all achievement is desire. - Napolean Hill",
  "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
  "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. - Thomas J. Watson",
  "All progress takes place outside the comfort zone. - Michael John Bobak",
  "You may only succeed if you desire succeeding; you may only fail if you do not mind failing. - Philippos",
  "Courage is resistance to fear, mastery of fear - not absence of fear. - Mark Twain",
  "Only put off until tomorrow what you are willing to die having left undone. - Pablo Picasso",
   "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, ever. This approach has never let me down, and it has made all the difference in my life. - Steve Jobs",
  "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily. - Zig Ziglar",
  "We become what we think about most of the time, and that's the strangest secret. - Earl Nightingale",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "The best reason to start an organization is to make meaning; to create a product or service to make the world a better place. - Guy Kawasaki",
  "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. - Martha Stewart",
  "It's not what you look at that matters, it's what you see.",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "The function of leadership is to produce more leaders, not more followers. - Ralph Nader",
  "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
  "As we look ahead into the next century, leaders will be those who empower others. - Bill Gates",
  "A real entrepreneur is somebody who has no safety net underneath them. - Henry Kravis",
  "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. - Mark Caine",
  "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy. - Tony Robbins",
  "When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid. - Audre Lorde",
  "Whenever you find yourself on the side of the majority, it is time to pause and reflect. - Mark Twain",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "Take up one idea. Make that one idea your life -- think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. - Swami Vivekananda",
  "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. - Dale Carnegie",
  "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much. -  Jim Rohn",
  "If you genuinely want something, don't wait for it -- teach yourself to be impatient. - Gurbaksh Chahal",
  "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
  "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! - T. Harv Eker",
  "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier, wish you were better. - Jim Rohn",
  "The number one reason people fail in life is because they listen to their friends, family, and neighbours. - Napoleon Hill",
  "The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who be sharing the adventure with them. - Denis Watiley",
  "Success does not consist in never making mistakes but in never making the same one a second time. - George ard Shaw",
  "I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. - Diane Ackerman",
  "You must expect great things of yourself before you can do them. - Michael Jordan",
  "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
  "People rarely succeed unless they have fun in what they are doing. - Dale Carnegie",
  "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul. - Ella Wheeler Wilcox",
  "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter. - Francis Chan",
  "You've got to get up every morning with determination if you're going to go to bed with satisfaction. - George Lorimer",
  "To be successful you must accept all challenges that come your way. You can't just accept the ones you like. - Mike Gafka",
  "Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others. -  John C. Maxwell",
  "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice. - Wayne Dyer",
  "To accomplish great things, we must not only act, but also dream, not only plan, but also believe.-  Anatole France",
  "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all. - Dale Carnegie",
  "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals. - Booker T. Washington",
  "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. - Jane Smiley",
  "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable. - Theodore N. Vail",
  "It is better to fail in originality than to succeed in imitation. - Herman Melville",
  "Fortune sides with him who dares. - Virgil",
  "Little minds are tamed and subdued by misfortune; but great minds rise above it. - Washington Irving",
  "Failure is the condiment that gives success its flavour. - Truman Capote",
  "Don't let what you cannot do interfere with what you can do. - John R. Wooden",
  "You may have to fight a battle more than once to win it. - Margaret Thatcher",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done. - Vince Lombardi", "The only people who never fail are those who never try. - Ilka Chase", "Failure is just another way to learn how to do something right. - Marian Wright Edelman", "I failed my way to success. - Thomas Edison", "Every failure brings with it the seed of an equivalent success. - Napoleon Hill", "Only those who dare to fail greatly can ever achieve greatly. - John F. Kennedy", "It is hard to fail, but it is worse never to have tried to succeed. - Theodore Roosevelt", "Imagination is more important than knowledge. - Albert Einstein", "Hold fast to dreams, for if dreams die, life is a broken winged bird that cannot fly. - ", "The future belongs to those who believe in the beauty of their dreams. - Eleanor ", "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry ", "You cannot depend on your eyes when your imagination is out of focus. - Mark Twain", "Commitment leads to action. Action brings your dream closer. - Marcia Wieder", "I never think of the future- it comes soon enough. - Albert Einstein", "Don't waste your life in doubts and fears: Spend yourself on the work before you, well assured that the right performance of this hour's duties will be the best preparation for the hours or ages that follow it. - Ralph Waldo Emerson", "Do not anticipate trouble or worry about what may never happen. Keep in the sunlight. - ", "Take time to deliberate; but when the time for action arrives, stop thinking and go in. - ", "The mind that is anxious about future events is miserable. - Seneca", "Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influences of each. - Henry David Thoreau", "The art of leadership is saying no, not yes. It is very easy to say yes. - Tony Blair", "A leader is a dealer in hope. - Napoleon Bonaparte", "While a good leader sustains momentum, a great leader increases it. - John C. Maxwell", "A general is just as good or just as bad as the troops under his command make him. - General Douglas MacArthur", "To do great things is difficult; but to command great things is more difficult. - Friedrich Nietzsche", "Leadership does not always wear the harness of compromise. - Woodrow Wilson", "Business opportunities are like buses- there's always another one coming. - Richard Branson", "I avoid looking forward or backward, and try to keep looking upward. - Charlotte Bronte", "The more difficulties one has to encounter, within and without, the more significant and the higher in inspiration his life will be. - Horace Bushnell", "Every artist was first an amateur. - Ralph Waldo Emerson", "I was always looking outside myself for strength and confidence, but it comes from within. It is there all of the time. - Anna Freud", "We can do anything we want to do if we stick to it long enough. - Helen Keller", "Our business in life is not to get ahead of others, but to get ahead of ourselves. - E. Joseph Cossman", "Insist on yourself. Never imitate. - Ralph Waldo Emerson", "Who looks outside, dreams. Who looks inside, awakes. - Carl Jung", "It is not easy to find happiness in ourselves, and it is not possible to find it elsewhere. - Agnes Repplier", "The only journey is the one within. - Rainer Maria Rilke", "Follow your honest convictions, and stay strong. - William ThackerayThe happiness of your life depends upon the quality of your thoughts; therefore guard accordingly. - Marcus Aurelius", "Action may not always bring happiness; but there is no happiness without action. - Benjamin Disraeli", "Happiness depends more on the inward disposition of mind than on outward circumstances. - Benjamin Franklin", "There is no happiness except in the realization that we have accomplished something. - Henry Ford", "Happiness is not a goal, but a by-product. - Eleanor Roosevelt", "Happiness is not a state to arrive at, but a manner of traveling. - Margaret Lee Runbeck", "Purpose is what gives life a meaning. - C. H. Parkhurst", "The significance of a man is not in what he attains but in what he longs to attain. - Kahlil Gibran", "In all things that you do, consider the end. - Solon", "Life can be pulled by goals just as surely as it can be pushed by drives. - Viktor Frankl", "The virtue lies in the struggle, not in the prize. - Richard Monckton Milnes", "To reach a port, we must sail- sail, not tie at anchor- sail, not drift. - Franklin Roosevelt", "Seeking success.", "Success is the child of audacity. - Benjamin Disraeli", "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi", "The secret of success is to know something nobody else knows. - Aristotle Onassis", "The surest way not to fail is to determine to succeed. - Richard Brinsley Sheridan", "I cannot give you the formula for success, but I can give you the formula for failure- which is: Try to please everybody. - Herbert Bayard Swope", "Careful thinking and hard work will solve nearly all your problems. Try and see for yourself. - Ullery", "Years teach us more than books. - Berthold Auerbach", "The only medicine for suffering, crime, and all the other woes of mankind, is wisdom. - Thomas Huxley", "The art of being wise is knowing what to overlook. - William James", "The great lesson is that the sacred is in the ordinary, that it is to be found in one's daily life, in one's neighbors, friends and family, in one's backyard. - Abraham Maslow", "A wise man learns by the mistakes of others, a fool by his own. - Latin proverb", "No man was ever wise by chance. - Seneca", "Setting goals.", "In everything the ends well defined are the secret of durable success. - Victor Cousins", "Arriving at one goal is the starting point to another. - John Dewey", "A goal is a dream with a deadline. - Napoleon Hill", "Most 'impossible' goals can be met simply by breaking them down into bite-size chunks, writing them down, believing them, and then going full speed ahead as if they were routine. - Don Lancaster", "Goals are the fuel in the furnace of achievement. - Brian Tracy", "We are what we repeatedly do. Excellence, therefore, is not an act but a habit. - Aristotle", "Take risks and you'll get the payoffs. Learn from your mistakes until you succeed. It's that simple. - Bobby Flay", "The best way out is always through. - Robert Frost", "You miss 100 percent of the shots you don't take. - Wayne Gretzky", "Nothing will ever be attempted if all possible objections must first be overcome. - Samuel Johnson", "Don't bunt. Aim out of the ballpark. - David Ogilvy"]